<?php
/**
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://www.gnu.org/licenses/.
 */

$labels = [];
$labels['copies']  = 'E-Mail-Kopien';
$labels['managecopies']  = 'E-Mail-Kopien verwalten';
$labels['copy_adresses']  = 'Jede neue E-Mail als Kopie an diese Adresse(n) schicken:';
$labels['copyinformation']  = 'Sie können mehrere Adressen durch Kommata getrennt eingeben.';

$messages = [];
$messages['errnosoaplogon'] = 'Es konnte keine Verbindung zum SOAP-Dienst bei all-inkl.com hergestellt werden.';
$messages['errpreviousinprogress'] = 'Die vorherige Anfrage wird noch bearbeitet, daher konnten keine Änderungen durchgeführt werden. Bitte versuchen Sie es nach kurzer Zeit nochmal.';
$messages['errnothingtodo'] = 'Es gibt keine Änderungen, die gespeichert werden müssen.';
$messages['errsyntaxincorrect'] = 'Es wurde ein Fehler in der Schreibweise der Adressen gefunden.';
$messages['errbadrequest'] = 'Es gab einen Fehler bei der SOAP-Anfrage.';
$messages['successfullysaved'] = 'Die Daten wurden gespeichert.';

?>
