<?php
/**
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://www.gnu.org/licenses/.
 */

$labels = [];
$labels['copies']  = 'Mail copies';
$labels['managecopies']  = 'Manage mail copies';
$labels['copy_adresses']  = 'Send a copy of incoming mail to:';
$labels['copyinformation']  = 'You can specify multiple addresses separated with comma.';

$messages = [];
$messages['errnosoaplogon'] = 'Unable to connect to SOAP server at all-inkl.com.';
$messages['errpreviousinprogress'] = 'The previous request is still in progress, therefore no changes have been made. Please try again in a few moments.';
$messages['errnothingtodo'] = 'There are no changes to save.';
$messages['errsyntaxincorrect'] = 'There was a syntax error in the input.';
$messages['errbadrequest'] = 'There was an error with the SOAP request.';
$messages['successfullysaved'] = 'The data has been saved.';

?>
